name: .Net Desktop

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore SofascoreWFcrawler.sln
    - name: Build project
      run: msbuild /p:Configuration=Release SofascoreWFcrawler.sln
